version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: mariadb_shinhan
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shinhan
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis
    container_name: redis_shinhan
    platform: linux/amd64
    restart: always
    ports:
      - "6380:6379"

volumes:
  mariadb-data: